DROP TABLE IF EXISTS `chart_master`;
CREATE TABLE `chart_master` (
  `account_code` varchar(15) NOT NULL DEFAULT '',
  `account_code2` varchar(15) NOT NULL DEFAULT '',
  `account_name` varchar(60) NOT NULL DEFAULT '',
  `account_type` varchar(10) NOT NULL DEFAULT '0',
  `inactive` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`account_code`),
  KEY `account_name` (`account_name`),
  KEY `accounts_by_type` (`account_type`,`account_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('1001', '1001', 'LAND', '1', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('1002', '1002', 'BUILDING', '1', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('1003', '1003', 'PLANT &amp; MACHINERY', '1', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('1004', '1004', 'TOOLS', '1', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('1005', '1005', 'FURNITURE &amp; FITTINGS', '1', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('1006', '1006', 'OFFICE EQUIPMENT', '1', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('1007', '1007', 'IT EQUIPMENT', '1', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('1008', '1008', 'SOLAR SYSTEM', '1', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('1050', '1050', 'PROVISION FOR DEPRECIATION - BUILDING', '1', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('1051', '1051', 'PROVISION FOR DEPRECIATION - PLANT &amp; MACHINERY', '1', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('1052', '1052', 'PROVISION FOR DEPRECIATION - TOOLS', '1', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('1053', '1053', 'PROVISION FOR DEPRECIATION - FURNITURE &amp; FITTINGS', '1', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('1054', '1054', 'PROVISION FOR DEPRECIATION - OFFICE EQUIPMENT', '1', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('1055', '1055', 'PROVISION FOR DEPRECIATION - IT EQUIPMENT', '1', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('1056', '1056', 'PROVISION FOR DEPRECIATION - SOLAR SYSTEM', '1', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('1100', '1100', 'INVENTORY', '2', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('1105', '1105', 'STOCKS OF WORK IN PROGRESS', '2', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('1110', '1110', 'LOAN - STAFF RECOVARABLES LOAN', '2', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('1111', '1111', 'LOAN - SHORT TERM LOAN RECEIVABLES', '2', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('1125', '1125', 'TRADE DEBTORS', '2', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('1150', '1150', 'BANK OF CEYLON- USD-0090608044', '2', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('1155', '1155', 'BANK OF CEYLON- LKR- 0089695095', '2', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('1160', '1160', 'PETTY CASH - SKY', '2', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('1161', '1161', 'PETTY CASH - MNT', '2', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('1162', '1162', 'PETTY CASH - IT', '2', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('1165', '1165', 'CASH IN HAND', '2', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('1210', '1210', 'COMMON SHARES', '5', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('1300', '1300', 'INVESTMENT - MR.KELUM BANDARA', '6', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('1301', '1301', 'INVESTMENT - MRS.NADEESHA SENANAYAKA', '6', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('1330', '1330', 'RETAINED EARNINGS - PRIOR YEARS', '6', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('1400', '1400', 'LOAN - LONG TERM LOAN PAYABLE', '3', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('1410', '1410', 'LOAN - LONG TERM LOAN PAYABLE DIRECTOR ACC - MRS.NADEESHA', '3', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('1420', '1420', 'LOAN - CUSTOMER ( MAS / HID / BDX )', '3', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('1440', '1440', 'DIRECTOR CURRENT ACC - MR.KELUM BANDARA', '3', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('1450', '1450', 'DIRECTOR CURRENT ACC - MRS.NADEESHA THARANGANI', '3', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('1500', '1500', 'TRADE CREDITORS', '4', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('1505', '1505', 'LOAN - SHORT TERM LOAN PAYABLE', '4', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('1515', '1515', 'ETF PAYABLE 3%', '4', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('1516', '1516', 'EPF PAYABLE 20%', '4', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('1517', '1517', 'NET SALARY PAYABLE', '4', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('1518', '1518', 'ACCOUNTING FEE PAYABLE', '4', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('1519', '1519', 'AUDIT FEE PAYABLE', '4', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('1520', '1520', 'ACCRUED EXPENSE - TELEPHONE', '4', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('1521', '1521', 'TAX PAYABLE', '4', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('1522', '1522', 'WATER PAYABLE', '4', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('1523', '1523', 'STAFF PAYABLE', '4', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2000', '2000', 'SALES', '7', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2100', '2100', 'DISCOUNTS GIVEN', '8', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2101', '2101', 'LOAN INTEREST RECEIVED', '8', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2102', '2102', 'FOREIGN EXCHANGE GAIN', '8', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2103', '2103', 'SHIPPING &amp; HANDLING REVENUE', '8', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2104', '2104', 'PROMPT PAYMENT DISCOUNTS', '8', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2105', '2105', 'BANK INTEREST RECEIVED', '8', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2200', '2200', 'OPENING STOCK', '9', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2201', '2201', 'PURCHASES ', '9', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2202', '2202', 'ELECTRICITY', '9', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2203', '2203', 'MARKETING', '9', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2204', '2204', 'BATA', '9', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2205', '2205', 'DISCOUNT RECEIVED', '9', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2213', '2213', 'EQUIPMENT MAINTENANCE', '9', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2214', '2214', 'PURCHASE PRICE VARIENCE', '9', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2215', '2215', 'DEPRECIATION- PLANT &amp; MACHINERY', '9', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2216', '2216', 'DEPRECIATION- TOOLS', '9', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2217', '2217', 'PURCHASE PRICE VARIANCE', '9', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2218', '2218', 'TEMPORARY WORKERS SALARY', '9', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2230', '2230', 'GROSS SALARY - PRODUCTION', '9', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2231', '2231', 'GROSS SALARY - CASUAL', '9', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2240', '2240', 'OVERTIME - PRODUCTION', '9', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2241', '2241', 'OVERTIME - CASUAL', '9', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2250', '2250', 'ALLOWANCES - PRODUCTION', '9', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2251', '2251', 'ALLOWANCES - CASUAL', '9', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2260', '2260', 'EPF- PRODUCTION 12%', '9', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2261', '2261', 'EPF - CASUAL 12%', '9', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2262', '2262', 'EPF 12% SURCHARGE FEE', '9', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2270', '2270', 'ETF - PRODUCTION 3%', '9', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2271', '2271', 'ETF - CASUAL 3%', '9', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2272', '2272', 'ETF 3% SURCHARGE FEE', '9', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2310', '2310', 'MOTOR VEHICLE MAINTENANCE', '10', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2311', '2311', 'TRAVELING &amp; TRANSPORT', '10', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2312', '2312', 'COURIER CHARGES', '10', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2313', '2313', 'BAD DEBTS', '10', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2314', '2314', 'VEHICLE FUEL', '10', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2315', '2315', 'SALES COMMISSION', '10', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2316', '2316', 'BOI PASS', '10', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2317', '2317', 'SHIPPING CHARGES', '10', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2400', '2400', 'DEPRECIATION- BUILDING', '11', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2401', '2401', 'DEPRECIATION- OFFICE EQUIPMENT', '11', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2402', '2402', 'DEPRECIATION- IT EQUIPMENT', '11', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2403', '2403', 'DEPRECIATION- FURNITURE &amp; FITTINGS', '11', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2404', '2404', 'DEPRECIATION - SOLAR SYSTEM', '11', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2405', '2405', 'WORKMENS INSURANCE', '11', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2406', '2406', 'WATER', '11', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2407', '2407', 'PRINTING &amp; STATIONERY', '11', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2408', '2408', 'OFFICE QUIPMENT MAINTENANCE', '11', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2409', '2409', 'BUILDING MAINTENANCE', '11', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2410', '2410', 'CHARITY DONATE', '11', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2411', '2411', 'TELEPHONE', '11', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2412', '2412', 'OTHER', '11', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2413', '2413', 'LOSS ON ASSET DISPOSAL ACCOUNT', '11', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2414', '2414', 'STAFF WELFARE', '11', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2415', '2415', 'ACCOUNTING CHARGES', '11', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2416', '2416', 'AUDIT FEE', '11', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2417', '2417', 'TAX EXPENSE', '11', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2420', '2420', 'GROSS SALARY- MANAGEMENT', '11', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2421', '2421', 'GROSS SALARY- DIRECTOR', '11', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2430', '2430', 'OVERTIME - MANAGEMENT', '11', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2431', '2431', 'OVERTIME - DIRECTOR', '11', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2440', '2440', 'ALLOWANCES - MANAGEMENT', '11', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2441', '2441', 'ALLOWANCES - DIRECTOR', '11', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2450', '2450', 'EPF - MANAGEMENT 12%', '11', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2460', '2460', 'ETF - MANAGEMENT 3%', '11', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2490', '2490', 'YEAR PROFIT / LOSS', '11', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2500', '2500', 'LOAN INTEREST CHARGES', '12', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2501', '2501', 'OVER DRAFT INTEREST ', '12', 0);
INSERT INTO `chart_master` (`account_code`, `account_code2`, `account_name`, `account_type`, `inactive`) VALUES ('2502', '2502', 'BANK CHARGES', '12', 0);