TRUNCATE TABLE `currencies`;
INSERT INTO `currencies` (`currency_name`, `currency_abbreviation`, `currency_symbol`, `country`, `hundredths_name`, `auto_exchange_rate_update`, `inactive`) VALUES ('Sri Lankan Rupees', 'LKR', 'LKR', 'Sri Lanka', 'Cents', 0, 0);
INSERT INTO `currencies` (`currency_name`, `currency_abbreviation`, `currency_symbol`, `country`, `hundredths_name`, `auto_exchange_rate_update`, `inactive`) VALUES ('US Dollars', 'USD', '$', 'United States', 'Cents', 1, 0);
TRUNCATE TABLE `reflines`;
INSERT INTO `reflines` (`id`, `trans_type`, `prefix`, `pattern`, `memo`, `default`, `inactive`) VALUES (1, 0, 'JE/', '{001}/{MM}/{YY}', '', 1, 0);
INSERT INTO `reflines` (`id`, `trans_type`, `prefix`, `pattern`, `memo`, `default`, `inactive`) VALUES (2, 1, 'BP/', '{001}/{MM}/{YY}', '', 1, 0);
INSERT INTO `reflines` (`id`, `trans_type`, `prefix`, `pattern`, `memo`, `default`, `inactive`) VALUES (3, 2, 'BD/', '{001}/{MM}/{YY}', '', 1, 0);
INSERT INTO `reflines` (`id`, `trans_type`, `prefix`, `pattern`, `memo`, `default`, `inactive`) VALUES (4, 4, 'FT/', '{001}/{MM}/{YY}', '', 1, 0);
INSERT INTO `reflines` (`id`, `trans_type`, `prefix`, `pattern`, `memo`, `default`, `inactive`) VALUES (5, 10, 'SI/', '{001}/{MM}/{YY}', '', 1, 0);
INSERT INTO `reflines` (`id`, `trans_type`, `prefix`, `pattern`, `memo`, `default`, `inactive`) VALUES (6, 11, 'CCN/', '{001}/{MM}/{YY}', '', 1, 0);
INSERT INTO `reflines` (`id`, `trans_type`, `prefix`, `pattern`, `memo`, `default`, `inactive`) VALUES (7, 12, 'CP/', '{001}/{MM}/{YY}', '', 1, 0);
INSERT INTO `reflines` (`id`, `trans_type`, `prefix`, `pattern`, `memo`, `default`, `inactive`) VALUES (8, 13, 'DN/', '{001}/{MM}/{YY}', '', 1, 0);
INSERT INTO `reflines` (`id`, `trans_type`, `prefix`, `pattern`, `memo`, `default`, `inactive`) VALUES (9, 16, 'LT/', '{001}/{MM}/{YY}', '', 1, 0);
INSERT INTO `reflines` (`id`, `trans_type`, `prefix`, `pattern`, `memo`, `default`, `inactive`) VALUES (10, 17, 'IA/', '{001}/{MM}/{YY}', '', 1, 0);
INSERT INTO `reflines` (`id`, `trans_type`, `prefix`, `pattern`, `memo`, `default`, `inactive`) VALUES (11, 18, 'PO/', '{001}/{MM}/{YY}', '', 1, 0);
INSERT INTO `reflines` (`id`, `trans_type`, `prefix`, `pattern`, `memo`, `default`, `inactive`) VALUES (12, 20, 'SI/', '{001}/{MM}/{YY}', '', 1, 0);
INSERT INTO `reflines` (`id`, `trans_type`, `prefix`, `pattern`, `memo`, `default`, `inactive`) VALUES (13, 21, 'SCN/', '{001}/{MM}/{YY}', '', 1, 0);
INSERT INTO `reflines` (`id`, `trans_type`, `prefix`, `pattern`, `memo`, `default`, `inactive`) VALUES (14, 22, 'SP/', '{001}/{MM}/{YY}', '', 1, 0);
INSERT INTO `reflines` (`id`, `trans_type`, `prefix`, `pattern`, `memo`, `default`, `inactive`) VALUES (15, 25, 'POD/', '{001}/{MM}/{YY}', '', 1, 0);
INSERT INTO `reflines` (`id`, `trans_type`, `prefix`, `pattern`, `memo`, `default`, `inactive`) VALUES (16, 26, 'WO/', '{001}/{MM}/{YY}', '', 1, 0);
INSERT INTO `reflines` (`id`, `trans_type`, `prefix`, `pattern`, `memo`, `default`, `inactive`) VALUES (17, 28, 'WOI/', '{001}/{MM}/{YY}', '', 1, 0);
INSERT INTO `reflines` (`id`, `trans_type`, `prefix`, `pattern`, `memo`, `default`, `inactive`) VALUES (18, 29, 'WOP/', '{001}/{MM}/{YY}', '', 1, 0);
INSERT INTO `reflines` (`id`, `trans_type`, `prefix`, `pattern`, `memo`, `default`, `inactive`) VALUES (19, 30, 'SO/', '{001}/{MM}/{YY}', '', 1, 0);
INSERT INTO `reflines` (`id`, `trans_type`, `prefix`, `pattern`, `memo`, `default`, `inactive`) VALUES (20, 32, 'SQ/', '{001}/{MM}/{YY}', '', 1, 0);
INSERT INTO `reflines` (`id`, `trans_type`, `prefix`, `pattern`, `memo`, `default`, `inactive`) VALUES (21, 35, 'CU/', '{001}/{MM}/{YY}', '', 1, 0);
INSERT INTO `reflines` (`id`, `trans_type`, `prefix`, `pattern`, `memo`, `default`, `inactive`) VALUES (22, 40, 'DI/', '{001}/{MM}/{YY}', '', 1, 0);
